name: workflows
on:
  push:
    branches:
      - master

jobs:
  build_docker_image:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          echo "Generated image tag is ${{ github.sha }}"
          docker build -t giddy87/springboot:app-${{ github.sha }} .
          echo "Docker build completed"

  push_image_to_registry:
    runs-on: self-hosted
    needs: build_docker_image
    steps:
      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Docker Image to Registry
        run: docker push giddy87/springboot:app-${{ github.sha }}

  deploy_to_dev:
    runs-on: self-hosted
    needs: push_image_to_registry
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "pipeline_user@thebulb.com"
          git config --global user.name "pipeline"
          
      - name: Update Kubernetes Manifests
        run: |
          git clone https://${{ secrets.USERNAME_TOKEN}}:${{ secrets.PIPELINE_TOKEN }}@github.com/giddy87/test-gitops.git
          cd test-gitops 
          sed -i "s/springboot:app-.*/springboot:app-${{ github.sha }}/g" springboot/deployment.yaml
          cat springboot/deployment.yaml
          git add springboot/deployment.yaml
          git commit -m "springboot test app Dev env k8s manifest file"
          git push origin main